# MNIST dataset

DATASET: !include dataset.yaml

MODEL: !include ../model/resnet18.yaml

TRAIN:
  EPOCH: 50
  BATCH_SIZE: 512
  OPTIMIZER:
    PARAM:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
  LR_SCHEDULER: !include ../lr_scheduler/sgdr.yaml
