
# MNIST dataset

DATASET: !include dataset.yaml
MODEL: !include ../model/resnet18.yaml

TRAIN:
  EPOCH: 10
  BATCH_SIZE: 256
  OPTIMIZER:
    PARAM:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
  LR_SCHEDULER: !include ../lr_scheduler/step.yaml
