
# MNIST dataset

DATASET: !include dataset.yaml
MODEL: !include ../model/standalone-selfattn/resnet26.yaml

TRAIN:
  EPOCH: 10
  EVAL_TRAIN: True
  BATCH_SIZE: 256
  OPTIMIZER:
    PARAM:
      lr: 0.01
      momentum: 0.9
      weight_decay: 1e-4
  LR_SCHEDULER:
    MODEK: 'multi_step'
    STEPS: [5, 8]
    GAMMA: 0.1
