# MNIST dataset

DATASET:
  PREFIX: 'mnist'
  MODULE: 'mytorch.data.mnist.mnist'
  PREPROCESS: 'mytorch.data.mnist.preprocess'
  IN_SIZE: (28, 28)
  OUT_SIZE: 10

MODEL:
  NAME: 'mytorch.model.fc.FullyConnectedNet'
  PARAM:
    LAYER: [512, 1024]

TRAIN:
  EPOCH: 10
  BATCH_SIZE: 512
  OPTIMIZER:
    PARAM:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
