
# MNIST dataset

DATASET:
  PREFIX: 'mnist'
  MODULE: 'mytorch.data.mnist.mnist'
  PREPROCESS: 'mytorch.preprocess.mnist'
  IN_SIZE: (28, 28)
  OUT_SIZE: 10

MODEL:
  NAME: 'mytorch.model.resnet.ResNet18'
  PARAM:
    INPUT_DEPTH: 1


TRAIN:
  EPOCH: 10
  BATCH_SIZE: 256
  OPTIMIZER:
    PARAM:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
