# MNIST dataset

DATASET:
  PREFIX: 'mnist'
  MODULE: 'mytorch.data.mnist.mnist'
  IN_SIZE: (28, 28)
  OUT_SIZE: 10

TRAIN:
  MODEL:
    NAME: 'mytorch.model.fc.FullyConnectedNet'
    PARAM:
      LAYER: [512, 1024]

  EPOCH: 10
  BATCH_SIZE: 512
  OPTIMIZER:
    PARAM:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
