# MNIST dataset

DATASET: !include dataset/mnist.yaml
MODEL: !include model/fc.yaml

TRAIN:
  EPOCH: 10
  BATCH_SIZE: 512
  OPTIMIZER:
    PARAM:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
